remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Onee-chan Website":
    - "https://onee-chan.info/"
  "Onee-chan on Lodestone":
    - "https://na.finalfantasyxiv.com/lodestone/community_finder/460849377274f26ea60dcb6b1529807ad6a0a749/"
